---
image: saschpe/android-sdk:29_29.0.2

before_script:
  - export GRADLE_USER_HOME=${PWD}/.gradle

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - test
  - integration
  - release
  - deploy


## Build stage

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug :mobile:assembleAndroidTest
  artifacts:
    expire_in: 1 day
    paths:
      - "*/build/**"

lintDebug:
  stage: build
  script:
    - ./gradlew lintDebug
  artifacts:
    paths:
      - "*/build/reports/lint-results*"

spotless:
  stage: build
  script:
    - ./gradlew spotlessCheck


## Test stage

testDebug:
  stage: test
  script:
    - ./gradlew testDebug
  dependencies:
    - assembleDebug
  artifacts:
    reports:
      junit: "*/build/test-results/**/TEST-*.xml"


## Integration stage

.firebase_template: &firebase
  image: registry.gitlab.com/saschpe/gamesale/ci-firebase
  stage: integration
  only:
    - schedules  # Only manual for now
  cache: {}
  dependencies:
    - assembleDebug
  environment:
    name: testing
    url: https://console.firebase.google.com/project/gamesale-1/testlab

firebaseInstrumentation:
  <<: *firebase
  script:
    - ./scripts/secret decrypt --password ${SECRETS_KEY} --firebase
    - ./scripts/firebase/test-lab
          --service-account config/firebase-test-lab-ci.json
          --type instrumentation

firebaseRobo:
  <<: *firebase
  script:
    - ./scripts/secret decrypt --password ${SECRETS_KEY} --firebase
    - ./scripts/firebase/test-lab
          --service-account config/firebase-test-lab-ci.json
          --type robo


## Release stage

assembleRelease:
  stage: release
  only:
    - master
  script:
    - ./scripts/secret decrypt --password ${SECRETS_KEY} --signing
    - ./gradlew bundleRelease
  dependencies: []
  artifacts:
    paths:
      - "*/build/outputs/**"


## Deploy stage

playStorePublish:
  stage: deploy
  only:
    - master
  script:
    - ./scripts/secret decrypt --password ${SECRETS_KEY} --signing
    - ./scripts/play-store/publish-app
  cache: {}
  dependencies:
    - assembleRelease
