#!/bin/bash
#
# Script to build the ci-firebase Docker image.
#
# Needs root privileges or 'docker' group membership

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${SCRIPT_DIR}/../inc.functions.sh"


# Constants for one particular image
DOCKER_FOLDER=config/docker-ci-firebase
DOCKER_IMAGE=registry.gitlab.com/lunchup/lunchup.android/ci-firebase
DOCKER_TAG=1


# Functions
function usage {
    echo -e "Usage: ${0} [OPTIONS]"
    echo -e "Options:"
    echo -e "  --push\t\t\t(optional)"
    exit 1
}


# Command-line arguments
docker_push=
while [[ $# -gt 0 ]] ; do
    key="$1"
    case ${key} in
    --push)
        docker_push=true
        ;;
    -h|--help)
        usage
        shift # past argument
        ;;
    *) # unknown option
        ;;
    esac
    shift # past argument or value
done


# Let's roll
image_tag=${DOCKER_TAG}

echo "Building image tag ${image_tag}..."
pushd ${DOCKER_FOLDER}
safe docker build \
    --tag ${DOCKER_IMAGE}:${image_tag} .
popd
if [[ ${docker_push} ]] ; then
    safe docker push ${DOCKER_IMAGE}:${image_tag}
fi

# Update 'latest' tag if script argument match defaults
echo "Tagging as 'latest'..."
safe docker tag ${DOCKER_IMAGE}:${image_tag} ${DOCKER_IMAGE}:latest
if [[ ${docker_push} ]] ; then
    safe docker push ${DOCKER_IMAGE}:latest
fi
