# docker build -t registry.gitlab.com/saschpe/gameon/ci-firebase .

FROM google/cloud-sdk:alpine
LABEL maintainer="Sascha Peilicke <sascha@peilicke.de>"

RUN apk --no-cache add \
        file \
        openssl
