name: Main CI
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Android problem matchers
        uses: jonasb/android-problem-matchers-action@v1
      - name: Build with Gradle
        env:
          SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
        run: |
          ./scripts/secret decrypt --password ${SECRETS_KEY} --google-services
          ./gradlew build
      - name: Publish to Play Store
        if: contains(github.ref, 'master')
        env:
          SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
        run: |
          ./scripts/secret decrypt --password ${SECRETS_KEY} --signing
          ./scripts/play-store/publish-app